# -*- coding: utf-8 -*-
"""Anos de dog

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cpgxQutW16AAr7jLNrVCvKbPfrvvMxjn
"""

anos = int(input("Digite quantos anos seu dog tem: "))
anos_c = 10.5 * anos
anos_b = (10.5 * 2) + 4 * (anos - 2)
if anos <= 2:
  print(f"A idade canina é: {anos_c}")
else:
  print(f"A idade canina é: {anos_b}")