# -*- coding: utf-8 -*-
"""Faixa de números

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WmM90x4ou7JP40ZTy_KSZgOq0O43MgQV
"""

number_1 = int(input("Digite um número: "))
number_2 = int(input("Digite outro número: "))
number_3 = int(input("Digite mais um número: "))
number_4 = int(input("Digite só mais um número: "))

soma = number_3 + number_4
multiplicacao = number_3 * number_4

if number_1 <= soma and soma <= number_2:
  if number_1 <= multiplicacao and multiplicacao <= number_2:
    print(f"Para a faixa de {number_1} à {number_2}",
    f"A soma {number_3} + {number_4}, que resulta em {soma}, está dentro da faixa",
    f"A multiplicação {number_3} * {number_4}, que resulta em {multiplicacao}, está dentro da faixa", sep="\n")
  elif multiplicacao > number_2 or multiplicacao < number_1:
    print(f"Para a faixa de {number_1} à {number_2}",
    f"A soma {number_3} + {number_4}, que resulta em {soma}, está dentro da faixa",
    f"A multiplicação {number_3} * {number_4}, que resulta em {multiplicacao}, está fora da faixa", sep="\n")
elif soma > number_2 or soma < number_1:
  if number_1 <= multiplicacao and multiplicacao <= number_2:
    print(f"Para a faixa de {number_1} à {number_2}",
    f"A soma {number_3} + {number_4}, que resulta em {soma}, está fora da faixa",
    f"A multiplicação {number_3} * {number_4}, que resulta em {multiplicacao}, está dentro da faixa", sep="\n")
  elif multiplicacao > number_2 or multiplicacao < number_1:
    print(f"Para a faixa de {number_1} à {number_2}",
    f"A soma {number_3} + {number_4}, que resulta em {soma}, está fora da faixa",
    f"A multiplicação {number_3} * {number_4}, que resulta em {multiplicacao}, está fora da faixa", sep="\n")